import io
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def export_docx(profile_data: dict, assessment_data: dict, roadmap_data: dict, user_name: str = "N/A") -> bytes:
    doc = Document()

    # Title
    title = doc.add_heading("Immigration Profile Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Disclaimer
    disclaimer = doc.add_paragraph()
    run = disclaimer.add_run("Disclaimer: This is not legal advice. Consult a qualified immigration attorney.")
    run.italic = True
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(102, 102, 102)

    # Profile Summary
    doc.add_heading("Profile Summary", level=1)
    table = doc.add_table(rows=5, cols=2)
    table.style = "Light Grid Accent 1"
    fields = [
        ("Name", user_name),
        ("Field", profile_data.get("field_of_expertise", "N/A")),
        ("Current Role", f"{profile_data.get('current_role', 'N/A')} at {profile_data.get('current_employer', 'N/A')}"),
        ("Target Pathway", profile_data.get("target_pathway", "N/A").upper()),
        ("Timeline", f"{profile_data.get('target_timeline_years', 'N/A')} years"),
    ]
    for i, (label, value) in enumerate(fields):
        table.cell(i, 0).text = label
        table.cell(i, 1).text = str(value)

    # Publications
    pubs = profile_data.get("publications", [])
    if pubs:
        doc.add_heading(f"Publications ({len(pubs)})", level=1)
        for p in pubs:
            doc.add_paragraph(f"{p['title']} — {p['venue']} ({p['year']}), Citations: {p.get('citation_count', 'N/A')}", style="List Bullet")

    # Assessment
    if assessment_data:
        doc.add_heading("Criteria Assessment", level=1)
        doc.add_paragraph(f"Overall Readiness: {assessment_data.get('overall_readiness', 'N/A')}")
        doc.add_paragraph(f"Criteria Met: {assessment_data.get('criteria_met_count', 0)} | Close: {assessment_data.get('criteria_close_count', 0)}")

        for cs in assessment_data.get("criteria_scores", []):
            doc.add_heading(f"Criterion {cs['criterion_number']}: {cs['criterion_name']} [{cs['strength'].upper()}]", level=2)
            doc.add_paragraph(f"Confidence: {cs['confidence']['overall']}%")
            doc.add_paragraph(f"Reasoning: {cs['confidence']['reasoning']}")
            if cs["gaps"]:
                doc.add_paragraph(f"Gaps: {', '.join(cs['gaps'])}")
            if cs["priority_actions"]:
                doc.add_paragraph(f"Priority Actions: {', '.join(cs['priority_actions'])}")

    # Roadmap
    if roadmap_data:
        doc.add_heading("Roadmap", level=1)
        for milestone in roadmap_data.get("milestones", []):
            doc.add_heading(milestone["quarter"], level=2)
            for action in milestone.get("actions", []):
                doc.add_paragraph(f"{action['action']}: {action['description']} (Effort: {action['effort_level']}, Impact: {action['impact_level']})", style="List Bullet")

        if roadmap_data.get("narrative_summary"):
            doc.add_heading("Strategy Summary", level=2)
            doc.add_paragraph(roadmap_data["narrative_summary"])

    doc.add_paragraph("")
    footer = doc.add_paragraph()
    run = footer.add_run("Generated by Immigration Roadmap Tool. This is not legal advice.")
    run.italic = True
    run.font.size = Pt(8)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
