def export_markdown(profile_data: dict, assessment_data: dict, roadmap_data: dict, user_name: str = "N/A") -> str:
    lines = []
    lines.append("# Immigration Profile Report")
    lines.append("")
    lines.append("> **Disclaimer:** This is not legal advice. Consult a qualified immigration attorney.")
    lines.append("")

    # Profile Summary
    lines.append("## Profile Summary")
    lines.append(f"- **Name:** {user_name}")
    lines.append(f"- **Field:** {profile_data.get('field_of_expertise', 'N/A')}")
    lines.append(f"- **Current Role:** {profile_data.get('current_role', 'N/A')} at {profile_data.get('current_employer', 'N/A')}")
    lines.append(f"- **Target Pathway:** {profile_data.get('target_pathway', 'N/A').upper()}")
    lines.append(f"- **Timeline:** {profile_data.get('target_timeline_years', 'N/A')} years")
    lines.append(f"- **Visa Status:** {profile_data.get('current_visa_status', 'N/A')}")
    lines.append("")

    # Publications
    pubs = profile_data.get("publications", [])
    if pubs:
        lines.append(f"## Publications ({len(pubs)})")
        for p in pubs:
            lines.append(f"- **{p['title']}** — {p['venue']} ({p['year']}), Citations: {p.get('citation_count', 'N/A')}")
        lines.append("")

    # Scholar Metrics
    if profile_data.get("h_index"):
        lines.append("## Scholar Metrics")
        lines.append(f"- H-index: {profile_data.get('h_index')}")
        lines.append(f"- Total Citations: {profile_data.get('total_citations')}")
        lines.append(f"- i10-index: {profile_data.get('i10_index')}")
        lines.append("")

    # Awards
    awards = profile_data.get("awards", [])
    if awards:
        lines.append(f"## Awards ({len(awards)})")
        for a in awards:
            lines.append(f"- **{a['name']}** — {a['granting_organization']} ({a['year']}, {a['scope']})")
        lines.append("")

    # Assessment
    if assessment_data:
        lines.append("## Criteria Assessment")
        lines.append(f"- **Overall Readiness:** {assessment_data.get('overall_readiness', 'N/A')}")
        lines.append(f"- **Criteria Met:** {assessment_data.get('criteria_met_count', 0)}")
        lines.append(f"- **Criteria Close:** {assessment_data.get('criteria_close_count', 0)}")
        lines.append("")
        for cs in assessment_data.get("criteria_scores", []):
            strength_emoji = {"strong": "[STRONG]", "moderate": "[MODERATE]", "weak": "[WEAK]", "none": "[NONE]"}.get(cs["strength"], "")
            lines.append(f"### Criterion {cs['criterion_number']}: {cs['criterion_name']} {strength_emoji}")
            lines.append(f"- **Confidence:** {cs['confidence']['overall']}%")
            lines.append(f"- **Reasoning:** {cs['confidence']['reasoning']}")
            if cs["evidence_found"]:
                lines.append(f"- **Evidence:** {', '.join(cs['evidence_found'])}")
            if cs["gaps"]:
                lines.append(f"- **Gaps:** {', '.join(cs['gaps'])}")
            if cs["priority_actions"]:
                lines.append(f"- **Actions:** {', '.join(cs['priority_actions'])}")
            lines.append("")

    # Roadmap
    if roadmap_data:
        lines.append("## Roadmap")
        lines.append(f"**Timeline:** {roadmap_data.get('timeline_years', 'N/A')} years")
        lines.append("")
        for milestone in roadmap_data.get("milestones", []):
            lines.append(f"### {milestone['quarter']}")
            for action in milestone.get("actions", []):
                lines.append(f"- **{action['action']}**: {action['description']} (Effort: {action['effort_level']}, Impact: {action['impact_level']}) — Criteria: {action['target_criterion']}")
            lines.append("")
        if roadmap_data.get("narrative_summary"):
            lines.append("## Strategy Summary")
            lines.append(roadmap_data["narrative_summary"])
            lines.append("")

    lines.append("---")
    lines.append("*Generated by Immigration Roadmap Tool. This is not legal advice.*")
    return "\n".join(lines)
