import io
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch


def export_pdf(profile_data: dict, assessment_data: dict, roadmap_data: dict, user_name: str = "N/A") -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("CustomTitle", parent=styles["Title"], fontSize=18, textColor=HexColor("#1a1a2e"))
    h2_style = ParagraphStyle("CustomH2", parent=styles["Heading2"], fontSize=14, textColor=HexColor("#16213e"))
    disclaimer_style = ParagraphStyle("Disclaimer", parent=styles["Normal"], fontSize=8, textColor=HexColor("#666666"), italic=True)

    story = []

    # Title
    story.append(Paragraph("Immigration Profile Report", title_style))
    story.append(Spacer(1, 12))
    story.append(Paragraph("<i>Disclaimer: This is not legal advice. Consult a qualified immigration attorney.</i>", disclaimer_style))
    story.append(Spacer(1, 20))

    # Profile Summary
    story.append(Paragraph("Profile Summary", h2_style))
    story.append(Spacer(1, 8))
    name = user_name
    field = profile_data.get("field_of_expertise", "N/A")
    role = profile_data.get("current_role", "N/A")
    employer = profile_data.get("current_employer", "N/A")
    pathway = profile_data.get("target_pathway", "N/A").upper()
    timeline = profile_data.get("target_timeline_years", "N/A")

    info_data = [
        ["Name", name], ["Field", field], ["Current Role", f"{role} at {employer}"],
        ["Target Pathway", pathway], ["Timeline", f"{timeline} years"],
    ]
    info_table = Table(info_data, colWidths=[1.5*inch, 4.5*inch])
    info_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 16))

    # Assessment Summary
    if assessment_data:
        story.append(Paragraph("Criteria Assessment", h2_style))
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"Overall Readiness: <b>{assessment_data.get('overall_readiness', 'N/A')}</b>", styles["Normal"]))
        story.append(Paragraph(f"Criteria Met: <b>{assessment_data.get('criteria_met_count', 0)}</b> | Close: <b>{assessment_data.get('criteria_close_count', 0)}</b>", styles["Normal"]))
        story.append(Spacer(1, 8))

        for cs in assessment_data.get("criteria_scores", []):
            story.append(Paragraph(f"<b>Criterion {cs['criterion_number']}: {cs['criterion_name']}</b> [{cs['strength'].upper()}] — {cs['confidence']['overall']}% confidence", styles["Normal"]))
            story.append(Spacer(1, 4))
        story.append(Spacer(1, 12))

    # Roadmap
    if roadmap_data:
        story.append(Paragraph("Roadmap", h2_style))
        story.append(Spacer(1, 8))
        for milestone in roadmap_data.get("milestones", []):
            story.append(Paragraph(f"<b>{milestone['quarter']}</b>", styles["Normal"]))
            for action in milestone.get("actions", []):
                story.append(Paragraph(f"  - {action['action']}: {action['description']}", styles["Normal"]))
            story.append(Spacer(1, 6))

        if roadmap_data.get("narrative_summary"):
            story.append(Spacer(1, 8))
            story.append(Paragraph("Strategy Summary", h2_style))
            story.append(Paragraph(roadmap_data["narrative_summary"], styles["Normal"]))

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by Immigration Roadmap Tool. This is not legal advice.", disclaimer_style))

    doc.build(story)
    return buffer.getvalue()
